const USStates: any = [
  { key: 1, value: 'AL', optionString: 'Alabama' },
  { key: 2, value: 'AK', optionString: 'Alaska' },
  { key: 3, value: 'AZ', optionString: 'Arizona' },
  { key: 4, value: 'AR', optionString: 'Arkansas' },
  { key: 5, value: 'CA', optionString: 'California' },
  { key: 6, value: 'CO', optionString: 'Colorado' },
  { key: 7, value: 'CT', optionString: 'Connecticut' },
  { key: 8, value: 'DE', optionString: 'Delaware' },
  { key: 9, value: 'FL', optionString: 'Florida' },
  { key: 10, value: 'GA', optionString: 'Georgia' },
  { key: 11, value: 'HI', optionString: 'Hawaii' },
  { key: 12, value: 'ID', optionString: 'Idaho' },
  { key: 13, value: 'IL', optionString: 'Illinois' },
  { key: 14, value: 'IN', optionString: 'Indiana' },
  { key: 15, value: 'IA', optionString: 'Iowa' },
  { key: 16, value: 'KS', optionString: 'Kansas' },
  { key: 17, value: 'KY', optionString: 'Kentucky' },
  { key: 18, value: 'LA', optionString: 'Louisiana' },
  { key: 19, value: 'ME', optionString: 'Maine' },
  { key: 20, value: 'MD', optionString: 'Maryland' },
  { key: 21, value: 'MA', optionString: 'Massachusetts' },
  { key: 22, value: 'MI', optionString: 'Michigan' },
  { key: 23, value: 'MN', optionString: 'Minnesota' },
  { key: 24, value: 'MS', optionString: 'Mississippi' },
  { key: 25, value: 'MO', optionString: 'Missouri' },
  { key: 26, value: 'MT', optionString: 'Montana' },
  { key: 27, value: 'NE', optionString: 'Nebraska' },
  { key: 28, value: 'NV', optionString: 'Nevada' },
  { key: 29, value: 'NH', optionString: 'New Hampshire' },
  { key: 30, value: 'NJ', optionString: 'New Jersey' },
  { key: 31, value: 'NM', optionString: 'New Mexico' },
  { key: 32, value: 'NY', optionString: 'New York' },
  { key: 33, value: 'NC', optionString: 'North Carolina' },
  { key: 34, value: 'ND', optionString: 'North Dakota' },
  { key: 35, value: 'OH', optionString: 'Ohio' },
  { key: 36, value: 'OK', optionString: 'Oklahoma' },
  { key: 37, value: 'OR', optionString: 'Oregon' },
  { key: 38, value: 'PA', optionString: 'Pennsylvania' },
  { key: 39, value: 'RI', optionString: 'Rhode Island' },
  { key: 40, value: 'SC', optionString: 'South Carolina' },
  { key: 41, value: 'SD', optionString: 'South Dakota' },
  { key: 42, value: 'TN', optionString: 'Tennessee' },
  { key: 43, value: 'TX', optionString: 'Texas' },
  { key: 44, value: 'UT', optionString: 'Utah' },
  { key: 45, value: 'VT', optionString: 'Vermont' },
  { key: 46, value: 'VA', optionString: 'Virginia' },
  { key: 47, value: 'WA', optionString: 'Washington' },
  { key: 48, value: 'WV', optionString: 'West Virginia' },
  { key: 49, value: 'WI', optionString: 'Wisconsin' },
  { key: 50, value: 'WY', optionString: 'Wyoming' },
  { key: 51, value: 'DC', optionString: 'District of Columbia' }
]

export default USStates
